// Generated by gencpp from file hivemind/plotting.msg
// DO NOT EDIT!


#ifndef HIVEMIND_MESSAGE_PLOTTING_H
#define HIVEMIND_MESSAGE_PLOTTING_H

#include <ros/service_traits.h>


#include <hivemind/plottingRequest.h>
#include <hivemind/plottingResponse.h>


namespace hivemind
{

struct plotting
{

typedef plottingRequest Request;
typedef plottingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct plotting
} // namespace hivemind


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hivemind::plotting > {
  static const char* value()
  {
    return "e7bc8cc39d0310ad493be8b4e35f3ce5";
  }

  static const char* value(const ::hivemind::plotting&) { return value(); }
};

template<>
struct DataType< ::hivemind::plotting > {
  static const char* value()
  {
    return "hivemind/plotting";
  }

  static const char* value(const ::hivemind::plotting&) { return value(); }
};


// service_traits::MD5Sum< ::hivemind::plottingRequest> should match 
// service_traits::MD5Sum< ::hivemind::plotting > 
template<>
struct MD5Sum< ::hivemind::plottingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hivemind::plotting >::value();
  }
  static const char* value(const ::hivemind::plottingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hivemind::plottingRequest> should match 
// service_traits::DataType< ::hivemind::plotting > 
template<>
struct DataType< ::hivemind::plottingRequest>
{
  static const char* value()
  {
    return DataType< ::hivemind::plotting >::value();
  }
  static const char* value(const ::hivemind::plottingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hivemind::plottingResponse> should match 
// service_traits::MD5Sum< ::hivemind::plotting > 
template<>
struct MD5Sum< ::hivemind::plottingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hivemind::plotting >::value();
  }
  static const char* value(const ::hivemind::plottingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hivemind::plottingResponse> should match 
// service_traits::DataType< ::hivemind::plotting > 
template<>
struct DataType< ::hivemind::plottingResponse>
{
  static const char* value()
  {
    return DataType< ::hivemind::plotting >::value();
  }
  static const char* value(const ::hivemind::plottingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIVEMIND_MESSAGE_PLOTTING_H
