// Generated by gencpp from file hivemind/plottingRequest.msg
// DO NOT EDIT!


#ifndef HIVEMIND_MESSAGE_PLOTTINGREQUEST_H
#define HIVEMIND_MESSAGE_PLOTTINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hivemind
{
template <class ContainerAllocator>
struct plottingRequest_
{
  typedef plottingRequest_<ContainerAllocator> Type;

  plottingRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , id(0)  {
    }
  plottingRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , id(0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::hivemind::plottingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hivemind::plottingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct plottingRequest_

typedef ::hivemind::plottingRequest_<std::allocator<void> > plottingRequest;

typedef boost::shared_ptr< ::hivemind::plottingRequest > plottingRequestPtr;
typedef boost::shared_ptr< ::hivemind::plottingRequest const> plottingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hivemind::plottingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hivemind::plottingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hivemind

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'hivemind': ['/home/jksun/surf-2019/jksun_ws/src/ros_hivemind/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hivemind::plottingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hivemind::plottingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hivemind::plottingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hivemind::plottingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hivemind::plottingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hivemind::plottingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hivemind::plottingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7bc8cc39d0310ad493be8b4e35f3ce5";
  }

  static const char* value(const ::hivemind::plottingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7bc8cc39d0310adULL;
  static const uint64_t static_value2 = 0x493be8b4e35f3ce5ULL;
};

template<class ContainerAllocator>
struct DataType< ::hivemind::plottingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hivemind/plottingRequest";
  }

  static const char* value(const ::hivemind::plottingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hivemind::plottingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"int32 id\n"
;
  }

  static const char* value(const ::hivemind::plottingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hivemind::plottingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct plottingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hivemind::plottingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hivemind::plottingRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIVEMIND_MESSAGE_PLOTTINGREQUEST_H
