// Generated by gencpp from file hivemind/reaction_wheel.msg
// DO NOT EDIT!


#ifndef HIVEMIND_MESSAGE_REACTION_WHEEL_H
#define HIVEMIND_MESSAGE_REACTION_WHEEL_H

#include <ros/service_traits.h>


#include <hivemind/reaction_wheelRequest.h>
#include <hivemind/reaction_wheelResponse.h>


namespace hivemind
{

struct reaction_wheel
{

typedef reaction_wheelRequest Request;
typedef reaction_wheelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reaction_wheel
} // namespace hivemind


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hivemind::reaction_wheel > {
  static const char* value()
  {
    return "2b5d6a6d532066fbb81f8a947d5d2ca3";
  }

  static const char* value(const ::hivemind::reaction_wheel&) { return value(); }
};

template<>
struct DataType< ::hivemind::reaction_wheel > {
  static const char* value()
  {
    return "hivemind/reaction_wheel";
  }

  static const char* value(const ::hivemind::reaction_wheel&) { return value(); }
};


// service_traits::MD5Sum< ::hivemind::reaction_wheelRequest> should match 
// service_traits::MD5Sum< ::hivemind::reaction_wheel > 
template<>
struct MD5Sum< ::hivemind::reaction_wheelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hivemind::reaction_wheel >::value();
  }
  static const char* value(const ::hivemind::reaction_wheelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hivemind::reaction_wheelRequest> should match 
// service_traits::DataType< ::hivemind::reaction_wheel > 
template<>
struct DataType< ::hivemind::reaction_wheelRequest>
{
  static const char* value()
  {
    return DataType< ::hivemind::reaction_wheel >::value();
  }
  static const char* value(const ::hivemind::reaction_wheelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hivemind::reaction_wheelResponse> should match 
// service_traits::MD5Sum< ::hivemind::reaction_wheel > 
template<>
struct MD5Sum< ::hivemind::reaction_wheelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hivemind::reaction_wheel >::value();
  }
  static const char* value(const ::hivemind::reaction_wheelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hivemind::reaction_wheelResponse> should match 
// service_traits::DataType< ::hivemind::reaction_wheel > 
template<>
struct DataType< ::hivemind::reaction_wheelResponse>
{
  static const char* value()
  {
    return DataType< ::hivemind::reaction_wheel >::value();
  }
  static const char* value(const ::hivemind::reaction_wheelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIVEMIND_MESSAGE_REACTION_WHEEL_H
