// Generated by gencpp from file hivemind/SATO.msg
// DO NOT EDIT!


#ifndef HIVEMIND_MESSAGE_SATO_H
#define HIVEMIND_MESSAGE_SATO_H

#include <ros/service_traits.h>


#include <hivemind/SATORequest.h>
#include <hivemind/SATOResponse.h>


namespace hivemind
{

struct SATO
{

typedef SATORequest Request;
typedef SATOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SATO
} // namespace hivemind


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hivemind::SATO > {
  static const char* value()
  {
    return "fbafa20672cd86d3d22a79748644c995";
  }

  static const char* value(const ::hivemind::SATO&) { return value(); }
};

template<>
struct DataType< ::hivemind::SATO > {
  static const char* value()
  {
    return "hivemind/SATO";
  }

  static const char* value(const ::hivemind::SATO&) { return value(); }
};


// service_traits::MD5Sum< ::hivemind::SATORequest> should match 
// service_traits::MD5Sum< ::hivemind::SATO > 
template<>
struct MD5Sum< ::hivemind::SATORequest>
{
  static const char* value()
  {
    return MD5Sum< ::hivemind::SATO >::value();
  }
  static const char* value(const ::hivemind::SATORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hivemind::SATORequest> should match 
// service_traits::DataType< ::hivemind::SATO > 
template<>
struct DataType< ::hivemind::SATORequest>
{
  static const char* value()
  {
    return DataType< ::hivemind::SATO >::value();
  }
  static const char* value(const ::hivemind::SATORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hivemind::SATOResponse> should match 
// service_traits::MD5Sum< ::hivemind::SATO > 
template<>
struct MD5Sum< ::hivemind::SATOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hivemind::SATO >::value();
  }
  static const char* value(const ::hivemind::SATOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hivemind::SATOResponse> should match 
// service_traits::DataType< ::hivemind::SATO > 
template<>
struct DataType< ::hivemind::SATOResponse>
{
  static const char* value()
  {
    return DataType< ::hivemind::SATO >::value();
  }
  static const char* value(const ::hivemind::SATOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIVEMIND_MESSAGE_SATO_H
