// Generated by gencpp from file hivemind/Velocity3.msg
// DO NOT EDIT!


#ifndef HIVEMIND_MESSAGE_VELOCITY3_H
#define HIVEMIND_MESSAGE_VELOCITY3_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace hivemind
{
template <class ContainerAllocator>
struct Velocity3_
{
  typedef Velocity3_<ContainerAllocator> Type;

  Velocity3_()
    : header()
    , v_x(0.0)
    , v_y(0.0)
    , v_theta(0.0)  {
    }
  Velocity3_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , v_x(0.0)
    , v_y(0.0)
    , v_theta(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _v_x_type;
  _v_x_type v_x;

   typedef float _v_y_type;
  _v_y_type v_y;

   typedef float _v_theta_type;
  _v_theta_type v_theta;





  typedef boost::shared_ptr< ::hivemind::Velocity3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hivemind::Velocity3_<ContainerAllocator> const> ConstPtr;

}; // struct Velocity3_

typedef ::hivemind::Velocity3_<std::allocator<void> > Velocity3;

typedef boost::shared_ptr< ::hivemind::Velocity3 > Velocity3Ptr;
typedef boost::shared_ptr< ::hivemind::Velocity3 const> Velocity3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hivemind::Velocity3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hivemind::Velocity3_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hivemind

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'hivemind': ['/home/jksun/surf-2019/jksun_ws/src/ros_hivemind/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hivemind::Velocity3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hivemind::Velocity3_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hivemind::Velocity3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hivemind::Velocity3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hivemind::Velocity3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hivemind::Velocity3_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hivemind::Velocity3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "38e5dd26a0c385d1458fff4afb16abfd";
  }

  static const char* value(const ::hivemind::Velocity3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x38e5dd26a0c385d1ULL;
  static const uint64_t static_value2 = 0x458fff4afb16abfdULL;
};

template<class ContainerAllocator>
struct DataType< ::hivemind::Velocity3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hivemind/Velocity3";
  }

  static const char* value(const ::hivemind::Velocity3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hivemind::Velocity3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Current velocity of a testbot, for testbot navigation to update its \"position\"\n"
"std_msgs/Header header\n"
"float32 v_x\n"
"float32 v_y\n"
"float32 v_theta\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::hivemind::Velocity3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hivemind::Velocity3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.v_x);
      stream.next(m.v_y);
      stream.next(m.v_theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Velocity3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hivemind::Velocity3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hivemind::Velocity3_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "v_x: ";
    Printer<float>::stream(s, indent + "  ", v.v_x);
    s << indent << "v_y: ";
    Printer<float>::stream(s, indent + "  ", v.v_y);
    s << indent << "v_theta: ";
    Printer<float>::stream(s, indent + "  ", v.v_theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIVEMIND_MESSAGE_VELOCITY3_H
