spacecraft_simulator:
  # Publish all joint states =================================================
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Publish all effort (force/torque) controllers ============================
  sc_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_anchor
