(cl:in-package hivemind-srv)
(cl:export '(X_0-VAL
          X_0
          X_F-VAL
          X_F
          U_MAX-VAL
          U_MAX
          NODES-VAL
          NODES
          RADII-VAL
          RADII
          NUM_STEPS-VAL
          NUM_STEPS
          NUM_THIS_PATH-VAL
          NUM_THIS_PATH
          TYPE_OF_DYNAMICS-VAL
          TYPE_OF_DYNAMICS
          DELTA_T-VAL
          DELTA_T
          WHICH_RADIUS_ARRAY-VAL
          WHICH_RADIUS_ARRAY
          THIS_PATH-VAL
          THIS_PATH
          X_OPT-VAL
          X_OPT
          U_OPT-VAL
          U_OPT
          COST-VAL
          COST
))