(cl:defpackage hivemind-srv
  (:use )
  (:export
   "CVXPY"
   "<CVXPY-REQUEST>"
   "CVXPY-REQUEST"
   "<CVXPY-RESPONSE>"
   "CVXPY-RESPONSE"
   "SATO"
   "<SATO-REQUEST>"
   "SATO-REQUEST"
   "<SATO-RESPONSE>"
   "SATO-RESPONSE"
   "PLOTTING"
   "<PLOTTING-REQUEST>"
   "PLOTTING-REQUEST"
   "<PLOTTING-RESPONSE>"
   "PLOTTING-RESPONSE"
   "REACTION_WHEEL"
   "<REACTION_WHEEL-REQUEST>"
   "REACTION_WHEEL-REQUEST"
   "<REACTION_WHEEL-RESPONSE>"
   "REACTION_WHEEL-RESPONSE"
  ))

