(cl:in-package hivemind-msg)
(cl:export '(HEADER-VAL
          HEADER
          FXMMZM-VAL
          FXMMZM
          FXMMZP-VAL
          FXMMZP
          FYMMZM-VAL
          FYMMZM
          FYMMZP-VAL
          FYMMZP
          FXPMZM-VAL
          FXPMZM
          FXPMZP-VAL
          FXPMZP
          FYPMZM-VAL
          FYPMZM
          FYPMZP-VAL
          FYPMZP
          FZPMYM-VAL
          FZPMYM
          FZMMYP-VAL
          FZMMYP
          FZPMXP-VAL
          FZPMXP
          FZMMXM-VAL
          FZMMXM
          FZPMYP-VAL
          FZPMYP
          FZMMYM-VAL
          FZMMYM
          FZMMXP-VAL
          FZMMXP
          FZPMXM-VAL
          FZPMXM
))